project:
  type: website

website:
  title: "ISSS624 (**CHIAYS**)"
  site-url: "https://isss624-chiays.netlify.app"
  
  navbar:
  
    left: 
      - icon: github
        href: https://github.com/
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
            
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
            
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
          - text: Take-home Exercise 2
         
    right:
      - href: index.qmd
        text: Home
      - about.qmd

    page-footer:
      - icon: tenor
        href: https://tenor.com/view/map-explore-trail-compass-colorful-gif-13844757

        
format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual


